server:
  port: 8085
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: microservicecloud-client
eureka:
  client:
    register-with-eureka: true  #註冊到Eureka註冊中心
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/    #單機版Eureka註冊中心